## Вычисления с помощью Numpy

In [53]:
import numpy as np

In [65]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3,10],
             [1, 7]])

rows, columns = a.shape

In [66]:
mean_a = np.mean(a, axis = 0)

mean_a 

array([2. , 8.4])

In [67]:
a_centered = a - mean_a 

a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [68]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

a_centered_sp

8.0

In [69]:
cov_a = a_centered_sp / (rows - 1)

cov_a

2.0

In [70]:
covar = np.cov(np.transpose(a))

covar

array([[1. , 2. ],
       [2. , 4.3]])

## Работа с данными в Pandas

In [12]:
import pandas as pd

In [15]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})



books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})

In [16]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')

authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [41]:
top5 = authors_price.nlargest(5, 'price')

top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [97]:
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})

authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

In [80]:
cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

authors_price['cover'] = cover

authors_price

author_id author_name            book_title  price    cover
6          3  Островский  Таланты и поклонники    290  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
5          3  Островский                 Гроза    370  твердая
0          1    Тургенев           Отцы и дети    450  твердая
4          2       Чехов       Дама с собачкой    450   мягкая
3          2       Чехов      Толстый и тонкий    500   мягкая

In [87]:
book_info = pd.pivot_table(authors_price, index = 'author_id', columns = 'cover', values = 'price')

book_info[['мягкая', 'твердая']] = book_info[['мягкая', 'твердая']].fillna(0)

book_info

cover      мягкая  твердая
author_id                 
1           325.0    450.0
2           475.0      0.0
3             0.0    330.0

In [86]:
book_info.pkl = book_info.to_pickle

book_info2 = pd.read_pickle('book_info.pkl')

book_info2

FileNotFoundError: [Errno 2] No such file or directory: 'book_info.pkl'